@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "s.praveen.cms.controller.AssignmentMgmtController#getAssignmentById(long)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "s.praveen.cms.controller.AssignmentMgmtController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_321882441 { 
   	label=praveen
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1915834990 { 
   	label=cms
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1265051707 { 
   	label=AssignmentMgmtController
	labeljust=l
	fillcolor=white
	style=filled
   
   AssignmentMgmtController1177992531XXXgetAssignmentById3327612[
	label="+ getAssignmentById()"
	style=filled
	fillcolor=white
	tooltip="AssignmentMgmtController

&#10;  Gets assignment by id.&#10; &#10;  @param id the id&#10;  @return the assignment by id&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_984077943 { 
   	label=AssignmentMgmtServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   AssignmentMgmtServiceImpl105350576XXXgetAssignmentById3327612[
	label="+ getAssignmentById()"
	style=filled
	fillcolor=white
	tooltip="AssignmentMgmtServiceImpl

&#10;  Gets assignment by id.&#10; &#10;  @param id the id&#10;  @return the assignment by id&#10;  @throws EnityNotFoundException the enity not found exception&#10; "
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AssignmentMgmtController1177992531XXXgetAssignmentById3327612 -> AssignmentMgmtServiceImpl105350576XXXgetAssignmentById3327612;
    
}
@enduml