@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "s.praveen.cms.controller.AssignmentMgmtController#createAssignment(AssignmentRequest)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "s.praveen.cms.controller.AssignmentMgmtController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_321882441 { 
   	label=praveen
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1915834990 { 
   	label=cms
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1265051707 { 
   	label=AssignmentMgmtController
	labeljust=l
	fillcolor=white
	style=filled
   
   AssignmentMgmtController1177992531XXXcreateAssignment1217295074[
	label="+ createAssignment()"
	style=filled
	fillcolor=white
	tooltip="AssignmentMgmtController

&#10;  Create assignment response entity.&#10; &#10;  @param request the request&#10;  @return the response entity&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1503865723 { 
   	label=CourseMgmtServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   CourseMgmtServiceImpl105350576XXXgetCourseById3327612[
	label="+ getCourseById()"
	style=filled
	fillcolor=white
	tooltip="CourseMgmtServiceImpl

&#10;  Gets course by id.&#10; &#10;  @param id the id&#10;  @return the course by id&#10;  @throws EnityNotFoundException the enity not found exception&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2063122741 { 
   	label=MappingTable
	labeljust=l
	fillcolor=white
	style=filled
   
   MappingTable1994342141XXXbuilder0[
	label="+ builder()"
	style=filled
	fillcolor=white
	tooltip="MappingTable

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_706272973 { 
   	label=AssignmentRequest
	labeljust=l
	fillcolor=white
	style=filled
   
   AssignmentRequest1044045465XXXcourseId0[
	label="+ courseId()"
	style=filled
	fillcolor=white
	tooltip="AssignmentRequest

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_733402199 { 
   	label=MappingTableServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MappingTableServiceImpl105350576XXXsubmitAssignment2080254016[
	label="+ submitAssignment()"
	style=filled
	fillcolor=white
	tooltip="MappingTableServiceImpl

&#10;  Submit assignment mapping table.&#10; &#10;  @param mappingTable the mapping table&#10;  @return the mapping table&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_984077943 { 
   	label=AssignmentMgmtServiceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074[
	label="+ addAssignment()"
	style=filled
	fillcolor=white
	tooltip="AssignmentMgmtServiceImpl

&#10;  Add assignment assignment.&#10; &#10;  @param request the request&#10;  @return the assignment&#10;  @throws EnityNotFoundException the enity not found exception&#10; "
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AssignmentMgmtController1177992531XXXcreateAssignment1217295074 -> AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074;
AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074 -> AssignmentRequest1044045465XXXcourseId0;
AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074 -> CourseMgmtServiceImpl105350576XXXgetCourseById3327612;
AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074 -> MappingTable1994342141XXXbuilder0;
AssignmentMgmtServiceImpl105350576XXXaddAssignment1217295074 -> MappingTableServiceImpl105350576XXXsubmitAssignment2080254016;
    
}
@enduml